title: SARS-CoV-2 Variants
author:
  name: David Giordano
  email: 3dgiordano@gmail.com
description: SARS-CoV-2 Variants by @3dgiordano
remote_theme: jekyll/minima

minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/3dgiordano" }
    - { platform: github, user_url: "https://github.com/3dgiordano/" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/davidgiordano/" }
